steps:
- name: gcr.io/$PROJECT_ID/remote-builder
  waitFor: ["-"]
  env:
    - INSTANCE_ARGS=--image-project centos-cloud --image-family centos-7 --preemptible
    - ZONE=asia-northeast2-a
    - USERNAME=cloud-user
    - COMMAND='id && pwd &&
yum -y install python3 wget &&
pip3 install ansible-bender && 
cd /etc/yum.repos.d/ &&
wget https://download.opensuse.org/repositories/devel:kubic:libcontainers:stable/CentOS_7/devel:kubic:libcontainers:stable.repo &&
yum -y install buildah podman &&
sed -e "s/^mountopt = \"nodev,metacopy=on\"/mountopt = \"nodev\"/" /etc/containers/storage.conf &&
systemctl start podman &&
pip uninstall ansible &&
pip3 install ansible &&
ansible-bender build main.yml'
