steps:
- name: gcr.io/$PROJECT_ID/remote-builder
  waitFor: ["-"]
  env:
    - INSTANCE_ARGS=--image-project centos-cloud --image-family centos-7 --preemptible
    - ZONE=asia-northeast2-a
    - USERNAME=cloud-user
      ### yum error occured
      # https://download.opensuse.org/repositories/devel%3A/kubic%3A/libcontainers%3A/stable/CentOS_7/x86_64/conmon-2.0.20-1.el7.x86_64.rpm: [Errno -1] Package does not match intended download. Suggestion: run yum --enablerepo=devel_kubic_libcontainers_stable clean metadata Trying other mirror.
      # Error downloading packages:
      # 2:conmon-2.0.20-1.el7.x86_64: [Errno 256] No more mirrors to try.
    - >
      COMMAND=id && 
      pwd && 
      cd workspace
      sudo bash -xe execroot.sh