steps:
- name: gcr.io/cloud-builders/gcloud
  entrypoint: 'bash'
  args: [ '-c', "gcloud secrets versions access latest --secret=dockerpassword --format='get(payload.data)' | tr '_-' '/+' | base64 -d > /workspace/decrypted-data.txt" ]

- name: gcr.io/$PROJECT_ID/remote-builder
  waitFor: ["-"]
  env:
#    - INSTANCE_ARGS=--image-project centos-cloud --image-family centos-7 --preemptible --machine-type e2-small --boot-disk-type=pd-ssd
    - INSTANCE_ARGS=--image-project centos-cloud --image-family centos-8 --preemptible --machine-type e2-medium --boot-disk-type=pd-ssd
    - ZONE=asia-northeast2-a
    - USERNAME=cloud-user
#    - password=`cat decrypted-data.txt`

      ### yum error occured
      # https://download.opensuse.org/repositories/devel%3A/kubic%3A/libcontainers%3A/stable/CentOS_7/x86_64/conmon-2.0.20-1.el7.x86_64.rpm: [Errno -1] Package does not match intended download. Suggestion: run yum --enablerepo=devel_kubic_libcontainers_stable clean metadata Trying other mirror.
      # Error downloading packages:
      # 2:conmon-2.0.20-1.el7.x86_64: [Errno 256] No more mirrors to try.
    - >
      COMMAND=id && 
      pwd && 
      cd workspace &&
      sudo bash -xe execroot.sh

# This step clones the exment-web-env repository
- name: 'gcr.io/cloud-builders/gcloud'
  id: Clone env repository
  entrypoint: /bin/sh
  args:
  - '-c'
  - |
    gcloud source repos clone exment-web-env && \
    cd exment-web-env && \
    git checkout candidate && \
    git config user.email $(gcloud auth list --filter=status:ACTIVE --format='value(account)')

# This step generates the new manifest
- name: 'gcr.io/cloud-builders/gcloud'
  id: Generate manifest
  entrypoint: /bin/sh
  args:
  - '-c'
  - |
     sed "s/GOOGLE_CLOUD_PROJECT/${PROJECT_ID}/g" kubernetes.yaml.tpl | \
     sed "s/COMMIT_SHA/${SHORT_SHA}/g" > exment-web-env/kubernetes.yaml

# This step pushes the manifest back to exment-web-env
- name: 'gcr.io/cloud-builders/gcloud'
  id: Push manifest
  entrypoint: /bin/sh
  args:
  - '-c'
  - |
    set -x && \
    cd exment-web-env && \
    git add kubernetes.yaml && \
    git commit -m "Deploying image gcr.io/${PROJECT_ID}/exment-web:${SHORT_SHA}
    Built from commit ${COMMIT_SHA} of repository exment-web-app
    Author: $(git log --format='%an <%ae>' -n 1 HEAD)" && \
    git push origin candidate

timeout: 3600s