steps:
- name: gcr.io/$PROJECT_ID/remote-builder
  waitFor: ["-"]
  env:
    - INSTANCE_ARGS=--image-project centos-cloud --image-family centos-7 --preemptible
    - ZONE=asia-northeast2-a
    - USERNAME=cloud-user
    - >
      COMMAND=id && 
      pwd && 
      sudo yum -y install python3 wget && 
      sudo pip3 install ansible-bender && 
      cd /etc/yum.repos.d/ && 
      sudo wget https://download.opensuse.org/repositories/devel:kubic:libcontainers:stable/CentOS_7/devel:kubic:libcontainers:stable.repo && 
      sudo yum -y install buildah podman && 
      sudo sed -i -e "s/^mountopt = \"nodev,metacopy=on\"/mountopt = \"nodev\"/" /etc/containers/storage.conf && 
      sudo systemctl start podman && 
      sudo pip uninstall ansible && 
      sudo pip3 install ansible && 
      sudo ansible-bender build main.yml