steps:
- name: gcr.io/$PROJECT_ID/remote-builder
  waitFor: ["-"]
  env:
    - INSTANCE_ARGS=--image-project centos-cloud --image-family centos-7 --preemptible
    - ZONE=asia-northeast2-a
    - USERNAME=cloud-user
    - >
      COMMAND=id && 
      pwd && 
      sudo su &&
      yum -y install python3 wget && 
      pip3 install ansible-bender selinux ansible && 
      ### yum error occured
      # https://download.opensuse.org/repositories/devel%3A/kubic%3A/libcontainers%3A/stable/CentOS_7/x86_64/conmon-2.0.20-1.el7.x86_64.rpm: [Errno -1] Package does not match intended download. Suggestion: run yum --enablerepo=devel_kubic_libcontainers_stable clean metadata Trying other mirror.
      # Error downloading packages:
      # 2:conmon-2.0.20-1.el7.x86_64: [Errno 256] No more mirrors to try.
      wget https://download.opensuse.org/repositories/devel%3A/kubic%3A/libcontainers%3A/stable/CentOS_7/x86_64/conmon-2.0.20-1.el7.x86_64.rpm
      rpm -ivh conmon-2.0.20-1.el7.x86_64.rpm
      cd /etc/yum.repos.d/ && 
      wget https://download.opensuse.org/repositories/devel:kubic:libcontainers:stable/CentOS_7/devel:kubic:libcontainers:stable.repo && 
      yum -y install buildah podman && 
      sed -i -e "s/^mountopt = \"nodev,metacopy=on\"/mountopt = \"nodev\"/" /etc/containers/storage.conf && 
      systemctl start podman && 
      ansible-bender build main.yml && 